/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6TMHBNbzSam
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export default function BookActions() {
  return (
    <div className="bg-[#2b2b2b] p-4 rounded-lg text-white w-[235px]">
      <div className="flex justify-between mb-4">
        <EyeIcon className="text-gray-400" />
        <HeartIcon className="text-gray-400" />
        <BookIcon className="text-gray-400" />
      </div>
      <div className="mb-4">
        <div className="text-sm font-semibold mb-2">Rate</div>
        <div className="flex">
          <StarIcon className="text-gray-400" />
          <StarIcon className="text-gray-400" />
          <StarIcon className="text-gray-400" />
          <StarIcon className="text-gray-400" />
          <StarIcon className="text-gray-400" />
        </div>
      </div>
      <div className="text-sm mb-4">
        <Button className="w-full mb-2" variant="ghost">
          Show your activity
        </Button>
        <Button className="w-full mb-2" variant="ghost">
          Show bobadams77's activity
        </Button>
        <Button className="w-full mb-2" variant="ghost">
          Review or log...
        </Button>
        <Button className="w-full" variant="ghost">
          Add this film to lists...
        </Button>
      </div>
      <div className="flex items-center justify-between bg-[#1b1b1b] p-2 rounded">
        <Input
          className="bg-transparent text-xs text-white placeholder-gray-400 border-none"
          placeholder="https://boxd.it/5RLb5"
          type="text"
        />
        <div className="flex space-x-2">
          <LinkIcon className="text-gray-400" />
          <PanelTopCloseIcon className="text-gray-400" />
          <FacebookIcon className="text-gray-400" />
        </div>
      </div>
    </div>
  )
}


function EyeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function HeartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  )
}


function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function LinkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  )
}


function PanelTopCloseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <line x1="3" x2="21" y1="9" y2="9" />
      <path d="m9 16 3-3 3 3" />
    </svg>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}
