/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OPffSoOXqwG
 */
import Link from "next/link";
import {
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenu,
} from "@/components/ui/navigation-menu";
import { CardContent, Card } from "@/components/ui/card";
import PopularBooks from "@/components/PopularBooks";
import { Suspense } from "react";

export function Home() {
  return (
    <>
      <PopularBooks bookLimit={6} />
      {/* <div>
        <h2 className="text-2xl font-bold">Recently Added</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4">
          <Card>
            <CardContent>
              <img
                alt="Book cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/200",
                  objectFit: "cover",
                }}
                width="150"
              />
              <h3 className="mt-2 text-lg font-semibold">Book Title</h3>
              <p className="text-gray-500">Author Name</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent>
              <img
                alt="Book cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/200",
                  objectFit: "cover",
                }}
                width="150"
              />
              <h3 className="mt-2 text-lg font-semibold">Book Title</h3>
              <p className="text-gray-500">Author Name</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent>
              <img
                alt="Book cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/200",
                  objectFit: "cover",
                }}
                width="150"
              />
              <h3 className="mt-2 text-lg font-semibold">Book Title</h3>
              <p className="text-gray-500">Author Name</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent>
              <img
                alt="Book cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/200",
                  objectFit: "cover",
                }}
                width="150"
              />
              <h3 className="mt-2 text-lg font-semibold">Book Title</h3>
              <p className="text-gray-500">Author Name</p>
            </CardContent>
          </Card>
        </div>
      </div> */}
      {/* <sectionF>
          <h2 className="text-2xl font-bold">News</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
            <Card>
              <CardContent>
                <img
                  alt="News image"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <h3 className="mt-2 text-lg font-semibold">News Title</h3>
                <p className="text-gray-500">News Description</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="News image"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <h3 className="mt-2 text-lg font-semibold">News Title</h3>
                <p className="text-gray-500">News Description</p>
              </CardContent>
            </Card>
          </div>
        </sectionF> */}
    </>
  );
}

function BookIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 1 6.5 2H20v20H6.5a2.5 0-5H20" />
    </svg>
  );
}
